add check for application file

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -91,6 +91,10 @@ runs:
       shell: bash
       run: |
         set -e
+        if ! [ -f /app/${{ inputs.application-file }} ]; then
+          echo "application file is missing"
+          exit 1
+        fi
         cp ./app/${{ inputs.application-file }} ./terragrunt/application.yaml
     # Setup go
     - name: Setup go
